#!/usr/bin/python3

# import json
# from sender import Sender
# from reader import Reader

# PORT = '/dev/ttyUSB0'
# BAUD = 9600

# reader = Reader(port=PORT, baud=BAUD)
# sender = Sender(port=PORT, baud=BAUD)

import logging
import datetime

# Only feed on each n minutes 
feedCountDown = 2
trackedMinutes = 0

def trackMinuteChange (minute):
  global trackedMinutes 
  trackedMinutes = minute

def countDown():
  global feedCountDown
  feedCountDown -= 1

def resetCountDown():
  global feedCountDown
  feedCountDown = 2

def shouldFeedPet(presence):
  return feedCountDown == 0 and presence

def aMinuteHasPassed(nowInMinutes):
  return nowInMinutes != trackedMinutes

def feedPet():
  logging.info('log: PET ALIMENTADO ON:')
  logging.info(datetime.datetime.now())

def getCurrentMinute():
  return datetime.datetime.now().strftime("%M")

while (1):
    # previous logic:
    # presence = json.loads(reader.getData())['presence']

    # if(presence == True):
    #     sender.alimentar()
    #     print('PET ALIMENTADO.\n')

    presence = True

    if(aMinuteHasPassed(getCurrentMinute())): 
      trackMinuteChange(getCurrentMinute())
      countDown()

    if (shouldFeedPet(presence)):
        feedPet()
        resetCountDown()